[project]
name = "panda-robotiq-collision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "meshcat>=0.3.2",
    "pin>=3.4.0",
]
